version: "3"

services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app:z
    command: >
      sh -c " python3 getdata.py"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=postgresspass
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresspass
